### ISSUE TITLE
Nginx 500 Internal Server Error

### ISSUE THREAD

**Issue by BuhtigithuB** [entercloudsuite/ansible-portus#2]
Followed : https://github.com/jsecchiero/letsencrypt-portus/blob/master/README.md

Trying to bring up the whole thing and when I try to access https://portus.domain.com, I fall on nginx 500 internal error...

Any idea where should I look?

**Comment by jsecchiero** [comment]
the domain must be a reachable domain from internet so letsencrypt can validate your certs

**Comment by BuhtigithuB** [comment]
Ok, any way to bypass letencrypt for the purpose of testing portus internally?

**Comment by jsecchiero** [comment]
imho using docker registry without trusted ssl is a bit trublesome.
You can also use DNS provider api without exposing the registry to the public, but actually is not implemented. 
Any PR is appreciated
es. https://certbot-dns-cloudflare.readthedocs.io/en/stable/

**Comment by BuhtigithuB** [comment]
Not sure about DNS-01 challenge seems overly complicated just for the sake of obtaining a encrypted connection between client and server and not clear text password flowing over the network (which I agree is essential). Maybe OpenSSL selfsigned certificate would do it in a simpler fashion? What would need to happen then? I have some almost entirely scripted/automated OpenSSL certificate issuance routine somewhere that I could contribute with good quality cert specs (same as Gmail certificate).

**Comment by jsecchiero** [comment]
Self signed certs doesn't work smoothly with docker. Try it yourself, you have to trust it somehow and is more complicated then using a world-wide trusted certs.

**Comment by BuhtigithuB** [comment]
Yeah, make a bunch of reading : 

- https://github.com/SUSE/Portus/issues/1770
- https://github.com/SUSE/Portus/issues/2050
- https://github.com/SUSE/Portus/issues/719 (Proposing many possibles solutions but not sure any will succeed in the end with all the complexity related to the docker ssl constrains)
- https://github.com/SUSE/Portus/issues/502
